In [7]:
#벡터와 행렬
import numpy as np

x = np.array([1,2,3])
x.__class__
print(x.shape, x.ndim)  #행렬수와 차원수 출력

W = np.array([[1,2,3],[4,5,6]])
print(W.shape, W.ndim)  #행렬수와 차원수 출력


(3,) 1
(2, 3) 2


In [11]:
#행렬의 원소별 연산
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
print(W+X,"\n\n", W*X)     #행렬 합과 행렬 곱 연산

[[ 1  3  5]
 [ 7  9 11]] 

 [[ 0  2  6]
 [12 20 30]]


In [15]:
#브로드캐스트 -> 형상이 다른 배열끼리의 연산
W = np.array([[1,2,3], [4,5,6]])
print(W * 10)

W = np.array([[1,3], [4,5]])
X = np.array([10,20])
print(W * X)


[[10 20 30]
 [40 50 60]]
[[ 10  60]
 [ 40 100]]


In [20]:
#백터의 내적과 행렬의 곱
##벡터의 내적
A = np.array([1,2,3])
B = np.array([0,1,2])
print(np.dot(A, B))

##행렬의 곱 -> 행렬의 형상에 주의
W = np.array([[1,2], [4,5]])
X = np.array([[4,1], [3,4]])
print(np.matmul(W, X)) 

8
[[10  9]
 [31 24]]
