In [10]:
#시그모이드 계층
import numpy as np

class Sigmoid :
    def __init__(self):
        self.params = []    #가중치, 편향 등 매개변수를 담는 리스트

    def forward(self, x):
        return 1 / (1 + np.exp(-x))     #순전파를 시그모이드 함수로 구현

In [16]:
#Affine 계층
class Affine :
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        return out

In [14]:
#2층 짜리 신경망 구현, Affine -> Sigmoid -> Affine 순
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)  
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O) 
        b2 = np.random.randn(O)
        
        # 레이어 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params
        
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x) #시그모이드 함수 적용
        return x

In [18]:
# 신경망 추론
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[ 0.80622395  1.23372034 -2.6277906 ]
 [ 1.06390857  0.71611162 -2.55684519]
 [ 0.3581306   1.13775156 -2.4854869 ]
 [ 0.49031511  1.15709814 -2.51369777]
 [ 0.73558369  1.65896478 -2.72248187]
 [ 1.05449377  0.82488603 -2.58541628]
 [ 0.96874515  1.05772392 -2.62720116]
 [ 1.12439515  1.06338763 -2.67132845]
 [ 0.33251676  0.93379046 -2.42742255]
 [ 0.66898145  1.02406483 -2.5211611 ]]
